import { apiRequest } from "./httpClient";
import type { DataRetentionSettings } from "../types/dataRetention";

// Admin → Settings → Data & retention. Owner role only. The schema table is
// generated by the backend from its data-schemas config.
const authorizationHeader = (accessToken: string) => ({ Authorization: `Bearer ${accessToken}` });

export const getDataRetentionRequest = (accessToken: string) =>
  apiRequest<DataRetentionSettings>("/admin/settings/data-retention", { headers: authorizationHeader(accessToken) });

// Only the AI query log period can change; the change is audited.
export const updateAiLogRetentionRequest = (accessToken: string, aiQueryLogsMonths: number) =>
  apiRequest<DataRetentionSettings>("/admin/settings/data-retention", {
    method: "PATCH",
    headers: authorizationHeader(accessToken),
    body: JSON.stringify({ aiQueryLogsMonths }),
  });
