import type { AdminUser } from "@/lib/types/adminUser";

export const adminUsers: AdminUser[] = [
  {
    id: "1",
    initials: "JO",
    name: "Jonah Okoye",
    email: "j.okoye@quiptech.com",
    role: "Technician",
    site: "Pit 4",
    lastActiveLabel: "12 min ago",
    status: "Active",
  },
  {
    id: "2",
    initials: "AS",
    name: "Ana Silva",
    email: "a.silva@quiptech.com",
    role: "Supervisor",
    site: "Pit 2",
    lastActiveLabel: "1 h ago",
    status: "Active",
  },
  {
    id: "3",
    initials: "TM",
    name: "Thabo Meyer",
    email: "t.meyer@quiptech.com",
    role: "Admin",
    site: "All sites",
    lastActiveLabel: "Now",
    status: "Active",
  },
  {
    id: "4",
    initials: "RM",
    name: "Rudo Mbeki",
    email: "r.mbeki@quiptech.com",
    role: "Technician",
    site: "Bench 7",
    lastActiveLabel: "Invited 18 Mar",
    status: "Invited",
  },
  {
    id: "5",
    initials: "DK",
    name: "Dieter Krause",
    email: "d.krause@quiptech.com",
    role: "Technician",
    site: "Pit 1",
    lastActiveLabel: "28 Feb",
    status: "Suspended",
  },
];
