import type { AdminDocument } from "@/lib/types/adminDocument";

export const adminDocuments: AdminDocument[] = [
  {
    id: "1",
    icon: "book",
    iconTone: "default",
    title: "CAT 793F service manual — vol 1",
    type: "Manual",
    indexedLabel: "02 Mar · 09:40",
    pages: "388",
    state: "Live",
  },
  {
    id: "2",
    icon: "book",
    iconTone: "default",
    title: "CAT 793F service manual — vol 2",
    type: "Manual",
    indexedLabel: "In progress · 68%",
    pages: "412",
    state: "Parsing",
  },
  {
    id: "3",
    icon: "alert",
    iconTone: "amber",
    title: "Bulletin 88 — revised charge pressure",
    type: "Bulletin",
    indexedLabel: "Awaiting review",
    pages: "2",
    state: "Draft",
  },
  {
    id: "4",
    icon: "tool",
    iconTone: "default",
    title: "Rear suspension cylinder recharge",
    type: "Procedure",
    indexedLabel: "14 Mar · 16:02",
    pages: "6",
    state: "Live",
  },
  {
    id: "5",
    icon: "x",
    iconTone: "danger",
    title: "Sandvik DR410 wiring diagrams",
    type: "Manual",
    indexedLabel: "Failed 18 Mar",
    pages: "—",
    state: "Failed",
  },
];
