-- Section 5b: the portal's Support cases screens. A case gets a readable
-- number (#1042), a priority, a category (drives its icon), who reported
-- it and when it was resolved. support_updates are the case's chat
-- messages; the reporter's messages show as "Reported", everyone else's as
-- "Support". Live delivery is the API's Socket.IO gateway — nothing here.

ALTER TABLE support_cases
  ADD COLUMN IF NOT EXISTS case_number bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1001),
  ADD COLUMN IF NOT EXISTS priority varchar NOT NULL DEFAULT 'P3',
  ADD COLUMN IF NOT EXISTS category varchar NOT NULL DEFAULT 'other',
  -- SET NULL so delete_user_account() (0039) still removes the reporter;
  -- the case stays with the organisation.
  ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS resolved_at timestamptz;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'support_cases_priority_check') THEN
    ALTER TABLE support_cases ADD CONSTRAINT support_cases_priority_check
      CHECK (priority IN ('P1', 'P2', 'P3'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'support_cases_category_check') THEN
    ALTER TABLE support_cases ADD CONSTRAINT support_cases_category_check
      CHECK (category IN ('alarm', 'leak', 'documentation', 'ai_answer', 'wear', 'data', 'other'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'support_cases_status_check') THEN
    ALTER TABLE support_cases ADD CONSTRAINT support_cases_status_check
      CHECK (status IN ('open', 'in_progress', 'resolved'));
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_support_cases_case_number ON support_cases (case_number);
CREATE INDEX IF NOT EXISTS idx_support_cases_tenant_status_updated
  ON support_cases (tenant_id, status, updated_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_support_updates_case_created
  ON support_updates (support_case_id, created_at);

INSERT INTO schema_migrations (version)
VALUES ('0051_support_case_workflow')
ON CONFLICT (version) DO NOTHING;
